/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Ability : active and passive abilities of character
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ability {
    #[serde(rename = "id")]
    pub id: String,
    /// 0 = ability is locked
    #[serde(rename = "level")]
    pub level: i32,
}

impl Ability {
    /// active and passive abilities of character
    pub fn new(id: String, level: i32) -> Ability {
        Ability {
            id,
            level,
        }
    }
}

