/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CampaignLevel {
    /// index of battle. Note that index=75 is available but no actual battle
    #[serde(rename = "battleIndex")]
    pub battle_index: i32,
    #[serde(rename = "attemptsLeft")]
    pub attempts_left: i32,
    #[serde(rename = "attemptsUsed")]
    pub attempts_used: i32,
}

impl CampaignLevel {
    pub fn new(battle_index: i32, attempts_left: i32, attempts_used: i32) -> CampaignLevel {
        CampaignLevel {
            battle_index,
            attempts_left,
            attempts_used,
        }
    }
}

