/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Guild {
    #[serde(rename = "guildId")]
    pub guild_id: String,
    #[serde(rename = "guildTag")]
    pub guild_tag: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "members")]
    pub members: Vec<models::GuildMember>,
    /// Lists guild raid seasons which can be queried at endpoint guildRaid
    #[serde(rename = "guildRaidSeasons")]
    pub guild_raid_seasons: Vec<i32>,
}

impl Guild {
    pub fn new(guild_id: String, guild_tag: String, name: String, level: i32, members: Vec<models::GuildMember>, guild_raid_seasons: Vec<i32>) -> Guild {
        Guild {
            guild_id,
            guild_tag,
            name,
            level,
            members,
            guild_raid_seasons,
        }
    }
}

