/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildResponse {
    #[serde(rename = "guild")]
    pub guild: Box<models::Guild>,
}

impl GuildResponse {
    pub fn new(guild: models::Guild) -> GuildResponse {
        GuildResponse {
            guild: Box::new(guild),
        }
    }
}

