/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildRaidResponse {
    #[serde(rename = "season")]
    pub season: i32,
    #[serde(rename = "seasonConfigId")]
    pub season_config_id: String,
    #[serde(rename = "entries")]
    pub entries: Vec<models::Raid>,
}

impl GuildRaidResponse {
    pub fn new(season: i32, season_config_id: String, entries: Vec<models::Raid>) -> GuildRaidResponse {
        GuildRaidResponse {
            season,
            season_config_id,
            entries,
        }
    }
}

