/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayerResponse {
    #[serde(rename = "player")]
    pub player: Box<models::Player>,
    #[serde(rename = "metaData")]
    pub meta_data: Box<models::PlayerMetaData>,
}

impl PlayerResponse {
    pub fn new(player: models::Player, meta_data: models::PlayerMetaData) -> PlayerResponse {
        PlayerResponse {
            player: Box::new(player),
            meta_data: Box::new(meta_data),
        }
    }
}

