/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayerDetails {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "powerLevel")]
    pub power_level: i32,
}

impl PlayerDetails {
    pub fn new(name: String, power_level: i32) -> PlayerDetails {
        PlayerDetails {
            name,
            power_level,
        }
    }
}

