/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicHeroDetail {
    #[serde(rename = "unitId")]
    pub unit_id: String,
    #[serde(rename = "power")]
    pub power: i32,
}

impl PublicHeroDetail {
    pub fn new(unit_id: String, power: i32) -> PublicHeroDetail {
        PublicHeroDetail {
            unit_id,
            power,
        }
    }
}

