/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequisitionOrders {
    #[serde(rename = "regular")]
    pub regular: i32,
    #[serde(rename = "blessed")]
    pub blessed: i32,
}

impl RequisitionOrders {
    pub fn new(regular: i32, blessed: i32) -> RequisitionOrders {
        RequisitionOrders {
            regular,
            blessed,
        }
    }
}

