/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Token {
    #[serde(rename = "current")]
    pub current: i32,
    #[serde(rename = "max")]
    pub max: i32,
    #[serde(rename = "nextTokenInSeconds", skip_serializing_if = "Option::is_none")]
    pub next_token_in_seconds: Option<i32>,
    #[serde(rename = "regenDelayInSeconds")]
    pub regen_delay_in_seconds: i32,
}

impl Token {
    pub fn new(current: i32, max: i32, regen_delay_in_seconds: i32) -> Token {
        Token {
            current,
            max,
            next_token_in_seconds: None,
            regen_delay_in_seconds,
        }
    }
}

