/*
 * Tacticus API
 *
 * This API provides read only access to various game related data.
 *
 * The version of the OpenAPI document: 0.1 BETA
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct XpBook {
    #[serde(rename = "id")]
    pub id: Id,
    #[serde(rename = "rarity")]
    pub rarity: Rarity,
    #[serde(rename = "amount")]
    pub amount: i32,
}

impl XpBook {
    pub fn new(id: Id, rarity: Rarity, amount: i32) -> XpBook {
        XpBook {
            id,
            rarity,
            amount,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Id {
    #[serde(rename = "xpCommon")]
    XpCommon,
    #[serde(rename = "xpUncommon")]
    XpUncommon,
    #[serde(rename = "xpRare")]
    XpRare,
    #[serde(rename = "xpEpic")]
    XpEpic,
    #[serde(rename = "xpLegendary")]
    XpLegendary,
}

impl Default for Id {
    fn default() -> Id {
        Self::XpCommon
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rarity {
    #[serde(rename = "Common")]
    Common,
    #[serde(rename = "Uncommon")]
    Uncommon,
    #[serde(rename = "Rare")]
    Rare,
    #[serde(rename = "Epic")]
    Epic,
    #[serde(rename = "Legendary")]
    Legendary,
}

impl Default for Rarity {
    fn default() -> Rarity {
        Self::Common
    }
}

